name: CI

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Push to master
        run: |
          echo "a" >> sample.txt
          git config user.email "popoppo39@gmail.com"
          git config user.name ${{ github.actor }}
          git commit -am "Hello!!"
          git push
        env:
          GITHUB_TOKEN: "invalid_token"
