name: rebase

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
#          fetch-depth: 0

      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: '2.9.1'

      - name: Update master and dev
        run: |
          git config user.email "popoppo39@gmail.com"
          git config user.name ${{ github.actor }}
          git log --pretty=oneline -5
          git pull origin master
          lein change version leiningen.release/bump-version release
          lein vcs commit
          lein vcs push
          git log --pretty=oneline -5
          git fetch origin dev
          git checkout dev
          git rebase master
          lein change version leiningen.release/bump-version
          lein vcs commit
          lein vcs push
