name: Manual workflow

on: push

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello"
      
    - name: Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,job,commit,ref
        custom_payload: |
          {
            attachments: [{
              color: 'good',
              text: `Success: workflow (${{github.workflow}}) in <${{github.event.repository.url}}|${{github.repository}}> (${{github.ref}}) ${{github.env.branch_name}} ${{github.job.env.branch_name}} ${{github.step.env.branch_name}}\n`
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        BRANCH_NAME: ${GITHUB_REF##*/}
      if: always()  
