name: Manual workflow

on: push

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{github.event}}"
      
    - name: Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,job,commit,ref
        custom_payload: |
          {
            attachments: [{
              title: 'Result'
              color: 'good',
              text: `Branch ${{github.ref}} has been deployed. ${{ process.env.GITHUB_REF }}`
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()  
