name: Manual workflow

on: workflow_dispatch # push

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"      

    - name: Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,job,commit,ref
        custom_payload: |
          {
            icon_emoji: ':recycle:',
            attachments: [{
              color: 'good',
              text: `Staging env is updated with ${{github.ref}} by ${{github.actor}}\nvia ${{github.workflow}} in <${{github.event.repository.url}}|${{github.repository}}>`
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        BRANCH_NAME: ${GITHUB_REF##*/}
      if: always()  
