name: Test workflow

on: push

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
    - name: Echo version
      id: version
      run: echo "::set-output name=v::$(echo \"1.2.3\" | sed -r 's/([0-9]+\.[0-9]+\.[0-9]+)-SNAPSHOT/\1/'"

    - name: Print actor name
      run: echo "${{ steps.version.outputs.v }}"
