name: Test workflow

on: push

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
    - name: Echo actor
      id: actor-name
      run: echo "::set-output name=actor::$(echo $GITHUB_CONTEXT | grep actor)"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: Print actor name
      run: echo "${{ steps.actor-name.outputs.actor }}"
